# Generated by Django 5.2.8 on 2025-11-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adresa',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='blocat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cod_postal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='data_nastere',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefon',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
